FROM centos:7

RUN yum update

RUN yum -y install epel-release && yum -y install http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum -y install httpd php71 php71-php
RUN /usr/sbin/httpd -k restart

# RUN echo "<?php phpinfo();" > /var/www/html/info.php

# EXPOSE 80

# ENTRYPOINT ['/usr/sbin/httpd']

CMD ["/usr/sbin/httpd","-D","FOREGROUND"]